export const ENABLE_LOCATION_REQUEST = 'ENABLE_LOCATION_REQUST';
export const ENABLE_LOCATION_SUCCESS = 'ENABLE_LOCATION_SUCCESS';
export const ENABLE_LOCATION_FAILURE = 'ENABLE_LOCATION_FAILURE';
export const ENABLE_NOTIFICATION_REQUEST = 'ENABLE_NOTIFICATION_REQUST';
export const ENABLE_NOTIFICATION_SUCCESS = 'ENABLE_NOTIFICATION_SUCCESS';
export const ENABLE_NOTIFICATION_FAILURE = 'ENABLE_NOTIFICATION_FAILURE';
